# Generated by Django 3.1.7 on 2021-03-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyzed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('analyzing_type', models.IntegerField(blank=True, choices=[(1, 'IPADDRESS'), (2, 'DOMAIN'), (3, 'FILEHASH')])),
                ('result_url', models.URLField(null=True)),
                ('last_analyzed', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'ERROR'), (3, 'RUNNING')], default=1)),
                ('malicous_level', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecuritySpecimen',
            fields=[
                ('specimen_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('analyzing_type', models.IntegerField(blank=True, choices=[(1, 'IPADDRESS'), (2, 'DOMAIN'), (3, 'FILEHASH')])),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ('name',),
            },
        ),
    ]
