# Generated by Django 3.1.7 on 2021-03-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210322_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=30)),
                ('analyzing_type', models.IntegerField(blank=True, choices=[(1, 'IPADDRESS'), (2, 'DOMAIN'), (3, 'FILEHASH')])),
                ('result_url', models.URLField(null=True)),
                ('last_analyzed', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'ERROR'), (3, 'RUNNING')], default=1)),
                ('malicous_level', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Analyzed Data List',
                'verbose_name_plural': 'Analyzed Data List',
                'ordering': ('result_url',),
            },
        ),
        migrations.DeleteModel(
            name='Analyzed',
        ),
        migrations.AlterModelOptions(
            name='securityspecimen',
            options={'ordering': ('specimen_id',), 'verbose_name': 'Specimen', 'verbose_name_plural': 'Specimen'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('name',), 'verbose_name': 'service', 'verbose_name_plural': 'service'},
        ),
    ]
