# Generated by Django 3.1.7 on 2021-03-23 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20210323_0511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecuritySpecimen',
        ),
    ]
