# Generated by Django 3.1.7 on 2021-03-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20210325_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datalist',
            options={'ordering': ('data_id',), 'verbose_name': 'Analyzed Data List', 'verbose_name_plural': 'Analyzed Data List'},
        ),
    ]
