# Generated by Django 3.1.7 on 2021-03-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20210325_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalist',
            name='slug',
        ),
    ]
