# Generated by Django 3.1.7 on 2021-03-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20210325_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalist',
            name='status',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'ERROR'), (3, 'RUNNING')], default=1),
        ),
    ]
