# Generated by Django 3.1.7 on 2021-03-25 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_datalist_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalist',
            name='status',
        ),
    ]
