# Generated by Django 3.1.7 on 2021-03-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_remove_datalist_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datalist',
            old_name='malicous_level',
            new_name='malicious_level',
        ),
    ]
