# Generated by Django 3.1.7 on 2021-04-24 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_auto_20210326_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datalist',
            options={'ordering': ('data_id',), 'verbose_name': 'OSINT Data', 'verbose_name_plural': 'OSINT Data List'},
        ),
        migrations.CreateModel(
            name='DataSearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('from_ip', models.CharField(max_length=16, verbose_name='from ipaddr')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.datalist')),
            ],
            options={
                'verbose_name': 'OSINT',
                'verbose_name_plural': 'OSINT Search History',
                'ordering': ('data',),
            },
        ),
    ]
