# Generated by Django 3.1.7 on 2021-04-24 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_auto_20210424_1256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataSearchHistory',
            new_name='DataSearchHistry',
        ),
    ]
