# Generated by Django 3.1.7 on 2021-04-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_auto_20210424_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalist',
            name='analyzing_type',
            field=models.IntegerField(choices=[(0, 'INVALID'), (1, 'IPADDRESS'), (2, 'DOMAIN'), (3, 'FILEHASH')], null=True),
        ),
    ]
