# Generated by Django 3.1.7 on 2021-04-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_auto_20210428_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalist',
            name='last_analyzed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
