# Generated by Django 3.1.7 on 2021-05-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_auto_20210428_1620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataSearchHistry',
            new_name='OsintSearchHistry',
        ),
    ]
