# Generated by Django 3.1.7 on 2021-05-12 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_auto_20210512_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsintSearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('from_ip', models.CharField(max_length=16, verbose_name='from ipaddr')),
                ('osint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.datalist')),
            ],
            options={
                'verbose_name': 'OSINT',
                'verbose_name_plural': 'OSINT Search History',
                'ordering': ('osint_id',),
            },
        ),
        migrations.CreateModel(
            name='VtSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100, null=True)),
                ('gui_url', models.URLField(null=True)),
                ('last_analyzed', models.DateTimeField(auto_now=True)),
                ('osint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.datalist')),
            ],
        ),
        migrations.DeleteModel(
            name='OsintSearchHistry',
        ),
    ]
