# Generated by Django 3.1.7 on 2021-05-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_auto_20210512_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vtsummary',
            options={'ordering': ('osint_id',), 'verbose_name': 'OSINT Data', 'verbose_name_plural': 'VT Summary'},
        ),
        migrations.AddField(
            model_name='vtsummary',
            name='malicious_level',
            field=models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'MALICIOUS'), (2, 'SUSPICIOUS'), (3, 'SAFE')], null=True),
        ),
        migrations.AddField(
            model_name='vtsummary',
            name='malicious_possibility',
            field=models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'MALICIOUS'), (2, 'SUSPICIOUS'), (3, 'SAFE')], null=True),
        ),
    ]
