# Generated by Django 3.1.7 on 2021-05-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_auto_20210513_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalist',
            name='data_id',
            field=models.CharField(max_length=100),
        ),
    ]
