# Generated by Django 3.1.7 on 2021-05-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_auto_20210513_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalist',
            name='data_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
