# Generated by Django 3.1.7 on 2021-05-15 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_auto_20210513_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vtsummary',
            options={'ordering': ('osint_id',), 'verbose_name': 'OSINT Data', 'verbose_name_plural': 'VirusTotal Summary'},
        ),
        migrations.CreateModel(
            name='VtComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100, null=True)),
                ('comment', models.CharField(max_length=1000, null=True)),
                ('vt_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.vtsummary')),
            ],
            options={
                'verbose_name': 'OSINT',
                'verbose_name_plural': 'VirusTotal Comments',
                'ordering': ('vt_summary',),
            },
        ),
    ]
