# Generated by Django 3.1.7 on 2021-05-16 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_auto_20210515_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100, null=True)),
                ('primary_ip', models.CharField(max_length=20, null=True)),
                ('domain', models.CharField(max_length=100)),
                ('server', models.CharField(max_length=20)),
                ('asname', models.CharField(max_length=20)),
                ('asn', models.CharField(max_length=20)),
                ('ptr', models.CharField(max_length=100)),
                ('screenshot', models.CharField(max_length=100)),
                ('osint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.datalist')),
            ],
            options={
                'verbose_name': 'OSINT',
                'verbose_name_plural': 'urlscan.io information',
                'ordering': ('osint_id',),
            },
        ),
    ]
