# Generated by Django 3.1.7 on 2021-05-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_remove_datalist_gui_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlscan',
            name='asname',
        ),
        migrations.AddField(
            model_name='urlscan',
            name='asnname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='urlscan',
            name='asn',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='urlscan',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='urlscan',
            name='domain',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='urlscan',
            name='ptr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='urlscan',
            name='screenshot',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='urlscan',
            name='server',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
