# Generated by Django 3.1.7 on 2021-05-22 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0028_auto_20210521_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlscan',
            name='domain',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='urlscan',
            name='osint_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.datalist', unique=True),
        ),
    ]
