# Generated by Django 3.1.7 on 2021-05-22 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0029_auto_20210522_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlscan',
            name='osint_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.datalist'),
        ),
    ]
