# Generated by Django 3.1.7 on 2021-05-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0030_auto_20210522_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vtsummary',
            old_name='last_analyzed',
            new_name='indexed_at',
        ),
    ]
