# Generated by Django 3.1.7 on 2021-05-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0031_auto_20210530_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vtsummary',
            name='indexed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
