# Generated by Django 3.1.7 on 2021-05-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0032_auto_20210530_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vtsummary',
            name='gui_url',
            field=models.URLField(null=True, unique=True),
        ),
    ]
